services:
  justwatch-telegram-bot:
    image: justwatch-telegram-bot:latest
    build: .
    container_name: justwatch-telegram-bot
    restart: unless-stopped
    environment:
      - PERSISTENCE_FILE=/config/persistence
    env_file: .env
    volumes:
      - ./config:/config

networks:
  default:
    name: justwatch-telegram-bot-network
    driver: bridge
