version: "3.9"
services:
  justwatch-telegram-bot:
    image: justwatch-telegram-bot:latest
    build: .
    container_name: justwatch-telegram-bot
    restart: unless-stopped
    environment:
      - PERSISTENCE_FILE=/config/persistence
    env_file: .env
    volumes:
      - ./config:/config
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
networks:
  default:
    name: justwatch-telegram-bot-network
    driver: bridge
